### ISSUE TITLE
[build] contents.rst not found

### ISSUE THREAD

**Issue by simogasp** [natowi/meshroom_doc#1]
Hi @natowi ,
thanks a lot for taking the time to write this documentation and now bringing it to this format which is more flexible than the google doc!

When I do `make html` (or any other one) I get the mentioned error.

```
Running Sphinx v1.3.6
making output directory...
loading pickled environment... not yet created
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 33 source files that are out of date
updating environment: 33 added, 0 changed, 0 removed
reading sources... [100%] tutorials/tutorials                                                                                                                                                                    

Sphinx error:
master file /home/alcov/dev/alicevision/meshroom_doc/source/contents.rst not found
Makefile:19: recipe for target 'html' failed
make: *** [html] Error 1
```

I checked and I see that u removed the file some commits ago but still I cannot find anything in the current code referencing to it. Do you have any idea?

Unrelated, maybe worth another issue, it would be better to remove the `build` directory as the files that can be generated should not be versioned.
What we could do, and I can surely help you with that, is to set up a Travis CI to remotely build and test the code and whenever there is a new versioned release of the manual we can set up Travis so it automatically publishes the pdf/html/whatnot on the release page of the repository (basically what we do for AV and meshroom). What do you think?

S.

**Comment by natowi** [comment]
Thank you for the feedback.

I was unable to recreate your contents.rst problem. [Edit: see #2]
Today I will update the source folder, fixing some missing links and references.

> Unrelated, maybe worth another issue, it would be better to remove the build directory as the files that can be generated should not be versioned.

I´ve added the folder to gitignore

> What we could do, and I can surely help you with that, is to set up a Travis CI to remotely build and test the code and whenever there is a new versioned release of the manual we can set up Travis so it automatically publishes the pdf/html/whatnot on the release page of the repository (basically what we do for AV and meshroom).

That would be really useful. I´ll come back to you on this, once I have a stable version without broken references and links.

**Comment by simogasp** [comment]
> I was unable to recreate your contents.rst problem. [Edit: see #2]

Thank you, it works now on my Mac, I could not test on my ubuntu machine but it should work (see below)

> 
> > Unrelated, maybe worth another issue, it would be better to remove the build directory as the files that can be generated should not be versioned.
> 
> I´ve added the folder to gitignore

Ok, but it should be removed from the repository as well, there is no point to have any product of the build in the repository.

> 
> 
> That would be really useful. I´ll come back to you on this, once I have a stable version without broken references and links.

You can have a look at my fork
https://github.com/simogasp/meshroom_doc/releases
The page of the releases is automatically generated and populated with the html doc and the pdf generated with latex every time a tag in the form `vX.Y.Z` is pushed to the repository. 

Thanks to the CI with Travis it also builds the doc with html and latex at every commit. This would be useful to validate the pull requests.
https://travis-ci.org/simogasp/meshroom_doc

If you agree I can go on with a pull request, I will explain what you need to set up to require the CI validation for merging PR and to publish the generated file for each release.

S.

PS
obviously, those releases are just tests, I haven't touched the content of the docs, I just tested the build - publish release code I added for Travis

**Comment by natowi** [comment]
I really like your setup. How about a bluejeans call tomorrow?

Do you have an idea on how to best format the CLI reference? At the moment it is formatted with sections (===) and subsections (----) resulting in them being numbered. Should I use table formatting as I did with the node reference?

Today I will be working on fixing the node reference tables and missing image references.

**Comment by simogasp** [comment]
> I really like your setup. How about a bluejeans call tomorrow?

maybe in the afternoon?
> 
> Do you have an idea on how to best format the CLI reference? At the moment it is formatted with sections (===) and subsections (----) resulting in them being numbered. Should I use table formatting as I did with the node reference?
> 

Yes I think it would be better. Maybe (as I'm a lazy guy ;-) ) we can rather find a way to generate those tables automatically from either the source code of the cli program or the help output of the CLI. That way, as they often change or new params are added it is easier to keep the doc updated.

**Comment by natowi** [comment]
> maybe in the afternoon?

Sounds good. Just send me an email with the link and time.

**Comment by natowi** [comment]
@simogasp you can ask Fabien or Yann for my mail address.

**Comment by simogasp** [comment]
hi @natowi sorry i'm a bit late. I don't have access to bluejeans, if it is ok for you we can do it on hangout (simone.gasparini@gmail.com) or skype (zorrob10)

**Comment by natowi** [comment]
@simogasp did you get my mail? (25.06.)

**Comment by simogasp** [comment]
yes, sorry I had some stuff that came up those days and I didn't contact you.
If you want we can schedule for the next week.

**Comment by natowi** [comment]
No problem, next week is just fine. You can send me an email with the details.

**Comment by natowi** [comment]
@simogasp I have fixed some errors and converted all images to jpg.
Can you check if there is still an error and open the PR?
