### ISSUE TITLE
Building documentation using Sphinx

### ISSUE THREAD

**Issue by vk2emq** [natowi/meshroom_doc#2]
Could you please provide more detail on how to build the meshroom doc ? Using Ubuntu I was able to install sphinx using the following commands in a terminal window 

sudo apt install python-pip

sudo pip install sphinx

After this I am unclear on what to do next.

As an input to the documentation - for the manual section on Tethering software 
the URLs below explain how to install the latest versions of entangle - version 2 and darktable version 2.6.2 on Ubuntu linux

http://ubuntuhandbook.org/?s=entangle

http://ubuntuhandbook.org/?s=darkroom

**Comment by natowi** [comment]
Thank you for the feedback.
Use the cli to navigate in the meshroom_doc directory and type in **make html**.
I did not test this on ubuntu, so if this does not work, use [sphinx-build](https://www.sphinx-doc.org/en/master/man/sphinx-build.html) from within the doc _source_ folder

**Comment by vk2emq** [comment]
Thanks for you reply  - I finally realised after having already downloaded the meshroom binary and not finding meshroom-doc in the meshroom files that I had to download the zip from your URL .... (one thing I have learned in writing instructions is never assume anything on the part of the viewer of said instructions ...)

NB I am running 64bit Xubuntu 18.04.02 with kernel 5.0.21 and meshroom 2019.1

Have now downloaded document zip and have installed pip and sphinx as below - but now experiencing problems with sphinx - any advice on how to resolve issues most appreciated
at URL
https://github.com/natowi/meshroom_doc
downloaded meshroom_doc-master.zip
extracted meshroom_doc-master.zip
 navigated to directory /meshroom_doc-master

vk2emq@cuda10:~/MESHROOM/meshroom_doc-master$ ls -la
total 32
drwxrwxr-x  4 vk2emq vk2emq 4096 Jun 23 19:10 .
drwxrwxr-x 11 vk2emq vk2emq 4096 Jun 23 19:15 ..
drwxrwxr-x  4 vk2emq vk2emq 4096 Jun 23 19:10 build
-rw-rw-r--  1 vk2emq vk2emq   34 Jun 23 19:10 .gitignore
-rw-rw-r--  1 vk2emq vk2emq  756 Jun 23 19:10 make.bat
-rw-rw-r--  1 vk2emq vk2emq  584 Jun 23 19:10 Makefile
-rw-rw-r--  1 vk2emq vk2emq  873 Jun 23 19:10 README.md
drwxrwxr-x 16 vk2emq vk2emq 4096 Jun 23 19:10 source

executed " make html "

vk2emq@cuda10:~/MESHROOM/meshroom_doc-master$ make html
Running Sphinx v1.8.5
loading pickled environment... failed: unsupported pickle protocol: 4
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 34 source files that are out of date
updating environment: 34 added, 0 changed, 0 removed
reading sources... [100%] tutorials/tutorials                                   
/home/vk2emq/MESHROOM/meshroom_doc-master/source/install/linux/linux.rst:31: WARNING: Inline emphasis start-string without end-string.
....

make output ends with

Sphinx error:
master file /home/vk2emq/MESHROOM/meshroom_doc-master/source/contents.rst not found
Makefile:19: recipe for target 'html' failed
make: *** [html] Error 2
vk2emq@cuda10:~/MESHROOM/meshroom_doc-master$

**Comment by natowi** [comment]
Thank you for the error report. Sphinx seems to be looking for contents.rst instead of index.rst ([details](https://github.com/rtfd/readthedocs.org/issues/2569#issuecomment-485117471)). Adding 
`# The master toctree document.`

`master_doc = 'index'`

to the conf.py (or renaming index.rst to contents.rst) should do the trick.

To resolve the "loading pickled environment... failed: unsupported pickle protocol: 4" error, you might need to [update ](https://stackoverflow.com/questions/55581191/importing-multiple-tables-from-files-in-sphinx-in-rst-format)to Python 3.4+.
