### ISSUE TITLE
latex build failed

### ISSUE THREAD

**Issue by natowi** [natowi/meshroom_doc#5]
```
cp latex/${LATEXNAME}.pdf ${INSTALL_PDF_FILENAME}
cp: cannot stat 'latex/Meshroom.pdf': No such file or directory
The command "cp latex/${LATEXNAME}.pdf ${INSTALL_PDF_FILENAME}" failed and exited with 1 during .
```
https://travis-ci.org/natowi/meshroom_doc

@simogasp Do you have an idea what the cause might be?

**Comment by simogasp** [comment]
Some stupid case insensitive BS...
https://travis-ci.org/simogasp/meshroom_doc/jobs/564062486#L1445
On my PC it generates a Meshroom.tex file and it complains if it is meshroom.tex
On travis it generates meshroom.tex and the command to generate the pdf uses Meshroom.tex and it does not fail!!

So long story short: it think changing `LATEXNAME=meshroom` works, but it is weird.
https://travis-ci.org/simogasp/meshroom_doc/jobs/564066325#L1852

**Comment by natowi** [comment]
Thanks, I was looking at the code, but could not spot an error. Did not think of case sensitivity.
